- name: create project home
  file: path={{ server_deploy_path }} state=directory mode=0755

- name: sync tomcat source
  synchronize: src={{ TOMCAT_APPLICATION }}/ dest={{ server_deploy_path }}/ checksum=yes archive=yes
